### ISSUE TITLE
why this lib is not using material-components-web-components

### ISSUE THREAD

**Issue by srghma** [aforemny/material-components-web-elm#116]
why this lib defines it's own custom dom elements instead of using https://github.com/material-components/material-components-web-components ?

**Comment by srghma** [comment]
the difference is that your approach doesnt use shadow-dom, it makes it easier to style (and maybe faster and easier to maintain)

**Comment by aforemny** [comment]
Hi @srghma, thank you for your question. Your observation is correct, us not using Shadow DOM is an important difference.

To provide some background and additional differences:

- We have actually tried using material-components-web-components and it went OK, see https://github.com/aforemny/elm-mwc. We have since then abandoned that approach in favor of this library for the following reasons:

- material-components-web-components was still in its infancy one year ago and it seemed questionable whether it would mature into a complete product or not.

- components of that library have been, as is the case with many UI frameworks, _interaction driven_ while Elm applications are _model driven_. This means that while the UI framework wants to change a checkbox' state upon interaction, we don't. This has generally not been an issue for when your model changes without user interaction, but it has generally been a nuisance for when the user interacts with a component but your model does not change. See in particular the following issue: https://github.com/aforemny/elm-mwc/issues/24

- material-components-web-components uses its own virtual DOM implementation called (Polymer's) LitElement. We use Elm's virtual DOM implementation and are thus not replicating that kind of code. This also means that we do not use Shadow DOM and our custom elements are not DOM leafs with regard to Elm's perspective.

Those three aspects together have influenced my decision in defining my own custom elements instead of basing this library upon material-components-web-components.

Let me know if you have any follow-up questions! :+1:

**Comment by srghma** [comment]
hi again @aforemny 

yes, I have question

where these files where taken from https://github.com/aforemny/material-components-web-elm/blob/d3aa83fced054b88d1e8ec1ed6f24e5b0c4d6c12/src/list/component.ts ?

it seems like they are from some google repo, but I cannot find

https://github.com/search?q=MDCListFactory+2018+Google+Inc+language%3Ajs&type=Code


P.S. I'm making fork of this lib for purescript-halogen framework that will reuse your js components

https://github.com/srghma/purescript-halogen-material-components-web

**Comment by srghma** [comment]
I did find myself https://github.com/material-components/material-components-web/blob/master/packages/mdc-list/component.ts , tnx anyway
