### ISSUE TITLE
Menu setOnClose Msg not firing when clicking anywhere outside of opened menu

### ISSUE THREAD

**Issue by Markloev** [aforemny/material-components-web-elm#142]
I'm trying to figure out how to use the mdc menu as a toggleable dropdown when clicking the dropdown arrow next to a username in the header to open up options, but I'm struggling to get the setOnClose event to even fire. Am I missing something obvious or is this a bug?

```
div [ Menu.surfaceAnchor ]
    [ mkBtn OpenUserDropdown "expand_more" Nothing
    , Menu.menu
        (Menu.config
            |> Menu.setOpen model.userDropdownOpened
            |> Menu.setOnClose CloseUserDropdown
        )
        [ List.list
            (List.config |> List.setWrapFocus True)
            (ListItem.listItem
                (ListItem.setOnClick
                    (GoToRoute RouteProfile)
                    ListItem.config
                )
                [ text "Profile" ]
            )
            [ ListItem.listItem
                (ListItem.setOnClick
                    (GoToRoute RouteSettings)
                    ListItem.config
                )
                [ text "Settings" ]
            , ListItem.listItem
                (ListItem.setOnClick
                    Msg.SignOut
                    ListItem.config
                )
                [ text "Sign Out" ]
            ]
        ]
    ]
```

**Comment by aforemny** [comment]
Hi @Markloev, `setMenuOnClose` should trigger if the menu is open and you click outside it. Here is an Ellie that demonstrates it: https://ellie-app.com/cK3kZMzkNBja1

Without the event listener `Menu.setOnClose Closed`, the menu would not close when clicking outside the menu.

Note that, because Ellie's body element only contains the button, you have to click into the narrow blue rectangle for it to work. Maybe your problem is related to something similar? The event listener for `Menu.setOnClose` is registered on the document's `<body>` element.

To assist you further, could you please send an Ellie reproducing your problem? Thanks!

**Comment by Markloev** [comment]
Ahhhh, that example was exactly what I needed to get a better idea of what was going on. I was importing "material-components-web-elm.js" at the top of index.js, but when I moved it to index.html in the <head> tags, the setOnClose event began firing.

Thanks!
