### ISSUE TITLE
Support for Data Table?

### ISSUE THREAD

**Issue by eweise** [aforemny/material-components-web-elm#49]
Hi!,

Will there be support for a data table? I notice the your previous elm-mdc has one but don't see in this library.

Thanks
Eric

**Comment by aforemny** [comment]
Hi @eweise, this library is a few version releases behind compared with elm-mdc which is why this library does not have data tables yet.

I am currently working on #26 and while doing that I am improving the work involved in updating this library to newer releases of MDC Web. I will make updating to newer releases of MDC Web a priority after that.

Pending any unforeseen obstacles (I have not studied the Data Table's source code yet), I would expect data tables to come soon.

**Comment by aforemny** [comment]
I have added Data Tables in 4ffdfa4a6dc5dbecfd4a7680d6f7c70153bbc101
